# Generated by Django 5.2.1 on 2025-05-14 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SGE', '0003_alter_evento_descricao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='hora_fim',
            new_name='horaFim',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='hora_inicio',
            new_name='horaInicio',
        ),
    ]
