# Generated by Django 5.2.1 on 2025-05-14 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGE', '0004_rename_hora_fim_evento_horafim_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='local',
            field=models.CharField(max_length=100),
        ),
    ]
