# Generated by Django 5.2.1 on 2025-05-16 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGE', '0005_alter_evento_local'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='telefone',
            field=models.CharField(max_length=15),
        ),
    ]
